# Spring AI MCP Server 配置
spring.ai.mcp.server.enabled=true
spring.ai.mcp.server.protocol=STATELESS
spring.ai.mcp.server.tool-callback-converter=true
spring.ai.mcp.server.name=mcp-server
spring.ai.mcp.server.version=1.0.0
spring.ai.mcp.server.type=SYNC
spring.ai.mcp.server.capabilities.resource=true
spring.ai.mcp.server.capabilities.tool=true
spring.ai.mcp.server.capabilities.prompt=true
spring.ai.mcp.server.capabilities.completion=true
spring.ai.mcp.server.request-timeout=30
spring.ai.mcp.server.annotation-scanner.enabled=true
spring.ai.mcp.server.stateless.mcp-endpoint=/mcp
spring.ai.mcp.server.stateless.disallow-delete=false
# harness 配置
spring.ai.harness.mcp.server.oss-prefix=mcp/workspaces/
spring.ai.harness.mcp.server.oss-bucket=bucket-ellm-uat

# Multipart limits
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB